services:
  - type: web
    name: Edulearn
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn Lms.wsgi:application --preload --workers=4 --threads=2 --timeout=120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Lms.settings
      - key: PYTHON_VERSION
        value: 3.11
